# Generated by Django 5.2.15 on 2026-06-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BussinesElement',
            new_name='BusinessElement',
        ),
        migrations.CreateModel(
            name='AccessRoleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_permission', models.BooleanField(default=False)),
                ('read_all_permission', models.BooleanField(default=False)),
                ('create_permission', models.BooleanField(default=False)),
                ('update_permission', models.BooleanField(default=False)),
                ('update_all_permission', models.BooleanField(default=False)),
                ('delete_permission', models.BooleanField(default=False)),
                ('delete_all_permission', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_rules', to='access_control.businesselement')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_role', to='access_control.role')),
            ],
            options={
                'ordering': ['role__code', 'element__code'],
            },
        ),
        migrations.DeleteModel(
            name='AccesRoleRule',
        ),
        migrations.AddConstraint(
            model_name='accessrolerule',
            constraint=models.UniqueConstraint(fields=('role', 'element'), name='unique_role_element_rule'),
        ),
    ]
